server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: cambio-service
  datasource:
    url: 'jdbc:postgresql://localhost:5432/cambio-service'
    username: 'postgres'
    password: '56657131'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  api-docs:
    path: cambio-service/v3/api-docs
