server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  retry:
    instances:
      foo-bar:
        max-attempts: 5
spring:
  application:
    name: book-service
  datasource:
    url: 'jdbc:postgresql://localhost:5432/book-service'
    username: 'postgres'
    password: '56657131'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
